In [4]:
import requests
from bs4 import BeautifulSoup as bs

import imp
imp.reload(requests)

C:\Users\zino0\AppData\Local\Temp\ipykernel_5420\2694513508.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp

In [6]:
# 실제 사이트에서 html정보를 받아와서 변수에 저장
data = requests.get('https://finance.naver.com/marketindex/exchangeList.naver').text

In [7]:
# BeautifulSoup을 이용해서 데이터를 파싱

soup = bs(data, 'html.parser')

In [8]:
print(soup)

<html lang="ko">
<head>
<title>네이버 증권</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/finance.css" rel="stylesheet" type="text/css"/>
<script language="javascript">document.domain="naver.com";</script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/js/info/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/js/lcslog.js" type="text/javascript"></script>
</head>
<body>
<div class="tbl_area">
<table border="1" class="tbl_exchange" summary="환전 고시 환율 리스트">
<caption>환전 고시 환율</caption>
<colgroup>
<col width="162"/>
<col width="92"/>
<col width="92"/>
<col width="92"/>
<col width="93"/>
<col width="92"/>
<col width="90"/>
</colgroup>
<thead>
<tr>
<th class="th_ex1" rowspan="2">
<a href="#" onclick="javascript:changeOrder('exchange'); return false;"><span>통화명</span></a></th>
<th class="th_ex2" rowspan="2"><span>매매기준율</span></th>
<th class="th_ex3" colspan="2"><span>현찰</span></th>
<th class="th_ex4" colspan="2"><span>송금</span></th>
<th class="th_ex6" rowspan="2"><span>미화환산율</span></th>
</tr>
<tr>
<th class="th_ex7"><span>사실 때 </span></th>
<th class="th_ex8"><span>파실 때 </span></th>
<th class="th_ex9"><span>보내실 때 </span></th>
<th class="th_ex10"><span>받으실 때</span></th>
</tr>
</thead>
<tbody>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_USDKRW', '1', event);" target="_parent">




					미국 USD

				</a></td>
<td class="sale">1,315.30</td>
<td>


						1,338.31

				</td>
<td>


						1,292.29

				</td>
<td>


						1,328.10

				</td>
<td>


						1,302.50

				</td>
<td>1.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EURKRW', '2', event);" target="_parent">




					유럽연합 EUR

				</a></td>
<td class="sale">1,444.59</td>
<td>


						1,473.33

				</td>
<td>


						1,415.85

				</td>
<td>


						1,459.03

				</td>
<td>


						1,430.15

				</td>
<td>1.098</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JPYKRW', '3', event);" target="_parent">

					일본 JPY (100엔)




				</a></td>
<td class="sale">981.46</td>
<td>


						998.63

				</td>
<td>


						964.29

				</td>
<td>


						991.07

				</td>
<td>


						971.85

				</td>
<td>0.746</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CNYKRW', '4', event);" target="_parent">




					중국 CNY

				</a></td>
<td class="sale">191.35</td>
<td>


						200.91

				</td>
<td>


						181.79

				</td>
<td>


						193.26

				</td>
<td>


						189.44

				</td>
<td>0.146</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HKDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HKDKRW', '5', event);" target="_parent">




					홍콩 HKD

				</a></td>
<td class="sale">167.61</td>
<td>


						170.91

				</td>
<td>


						164.31

				</td>
<td>


						169.28

				</td>
<td>


						165.94

				</td>
<td>0.127</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TWDKRW', '6', event);" target="_parent">




					대만 TWD

				</a></td>
<td class="sale">43.13</td>
<td>


						48.78

				</td>
<td>


						38.82

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.033</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_GBPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_GBPKRW', '7', event);" target="_parent">




					영국 GBP

				</a></td>
<td class="sale">1,635.25</td>
<td>


						1,667.46

				</td>
<td>


						1,603.04

				</td>
<td>


						1,651.60

				</td>
<td>


						1,618.90

				</td>
<td>1.243</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_OMRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_OMRKRW', '8', event);" target="_parent">




					오만 OMR

				</a></td>
<td class="sale">3,416.19</td>
<td>


						3,720.23

				</td>
<td>


						3,211.22

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>2.597</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CADKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CADKRW', '9', event);" target="_parent">




					캐나다 CAD

				</a></td>
<td class="sale">982.63</td>
<td>


						1,001.98

				</td>
<td>


						963.28

				</td>
<td>


						992.45

				</td>
<td>


						972.81

				</td>
<td>0.747</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CHFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CHFKRW', '10', event);" target="_parent">




					스위스 CHF

				</a></td>
<td class="sale">1,467.80</td>
<td>


						1,496.71

				</td>
<td>


						1,438.89

				</td>
<td>


						1,482.47

				</td>
<td>


						1,453.13

				</td>
<td>1.116</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SEKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SEKKRW', '11', event);" target="_parent">




					스웨덴 SEK

				</a></td>
<td class="sale">127.62</td>
<td>


						130.74

				</td>
<td>


						124.50

				</td>
<td>


						128.89

				</td>
<td>


						126.35

				</td>
<td>0.097</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AUDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AUDKRW', '12', event);" target="_parent">




					호주 AUD

				</a></td>
<td class="sale">886.58</td>
<td>


						904.04

				</td>
<td>


						869.12

				</td>
<td>


						895.44

				</td>
<td>


						877.72

				</td>
<td>0.674</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NZDKRW', '13', event);" target="_parent">




					뉴질랜드 NZD

				</a></td>
<td class="sale">817.59</td>
<td>


						833.69

				</td>
<td>


						801.49

				</td>
<td>


						825.76

				</td>
<td>


						809.42

				</td>
<td>0.622</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CZKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CZKKRW', '14', event);" target="_parent">




					체코 CZK

				</a></td>
<td class="sale">61.61</td>
<td>


						66.84

				</td>
<td>


						56.07

				</td>
<td>


						62.28

				</td>
<td>


						60.94

				</td>
<td>0.047</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CLPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CLPKRW', '15', event);" target="_parent">




					칠레 CLP

				</a></td>
<td class="sale">1.65</td>
<td>


						1.81

				</td>
<td>


						1.49

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.001</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TRYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TRYKRW', '16', event);" target="_parent">




					튀르키예 TRY

				</a></td>
<td class="sale">67.81</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						68.55

				</td>
<td>


						67.07

				</td>
<td>0.052</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MNTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MNTKRW', '17', event);" target="_parent">




					몽골 MNT

				</a></td>
<td class="sale">0.37</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ILSKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ILSKRW', '18', event);" target="_parent">




					이스라엘 ILS

				</a></td>
<td class="sale">360.69</td>
<td>


						396.75

				</td>
<td>


						331.84

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DKKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DKKKRW', '19', event);" target="_parent">




					덴마크 DKK

				</a></td>
<td class="sale">193.86</td>
<td>


						198.60

				</td>
<td>


						189.12

				</td>
<td>


						195.79

				</td>
<td>


						191.93

				</td>
<td>0.147</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NOKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NOKKRW', '20', event);" target="_parent">




					노르웨이 NOK

				</a></td>
<td class="sale">125.62</td>
<td>


						128.69

				</td>
<td>


						122.55

				</td>
<td>


						126.87

				</td>
<td>


						124.37

				</td>
<td>0.096</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SARKRW', '21', event);" target="_parent">




					사우디아라비아 SAR

				</a></td>
<td class="sale">350.68</td>
<td>


						372.77

				</td>
<td>


						326.49

				</td>
<td>


						354.18

				</td>
<td>


						347.18

				</td>
<td>0.267</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KWDKRW', '22', event);" target="_parent">




					쿠웨이트 KWD

				</a></td>
<td class="sale">4,292.19</td>
<td>


						4,571.18

				</td>
<td>


						3,948.82

				</td>
<td>


						4,335.11

				</td>
<td>


						4,249.27

				</td>
<td>3.263</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BHDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BHDKRW', '23', event);" target="_parent">




					바레인 BHD

				</a></td>
<td class="sale">3,488.58</td>
<td>


						3,711.84

				</td>
<td>


						3,209.50

				</td>
<td>


						3,523.46

				</td>
<td>


						3,453.70

				</td>
<td>2.652</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AEDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AEDKRW', '24', event);" target="_parent">




					아랍에미리트 AED

				</a></td>
<td class="sale">358.16</td>
<td>


						377.85

				</td>
<td>


						333.45

				</td>
<td>


						361.74

				</td>
<td>


						354.58

				</td>
<td>0.272</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JODKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JODKRW', '25', event);" target="_parent">




					요르단 JOD

				</a></td>
<td class="sale">1,854.10</td>
<td>


						2,019.11

				</td>
<td>


						1,705.78

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>1.410</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EGPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EGPKRW', '26', event);" target="_parent">




					이집트 EGP

				</a></td>
<td class="sale">42.57</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.032</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_THBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_THBKRW', '27', event);" target="_parent">




					태국 THB

				</a></td>
<td class="sale">38.41</td>
<td>


						40.33

				</td>
<td>


						36.11

				</td>
<td>


						38.79

				</td>
<td>


						38.03

				</td>
<td>0.029</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SGDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SGDKRW', '28', event);" target="_parent">




					싱가포르 SGD

				</a></td>
<td class="sale">987.65</td>
<td>


						1,007.30

				</td>
<td>


						968.00

				</td>
<td>


						997.52

				</td>
<td>


						977.78

				</td>
<td>0.751</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MYRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MYRKRW', '29', event);" target="_parent">




					말레이시아 MYR

				</a></td>
<td class="sale">296.94</td>
<td>


						315.64

				</td>
<td>


						274.97

				</td>
<td>

						N/A


				</td>
<td>


						293.98

				</td>
<td>0.226</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_IDRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_IDRKRW', '30', event);" target="_parent">


					인도네시아 IDR 100



				</a></td>
<td class="sale">8.88</td>
<td>


						9.76

				</td>
<td>


						8.00

				</td>
<td>


						8.96

				</td>
<td>


						8.80

				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_QARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_QARKRW', '31', event);" target="_parent">




					카타르 QAR

				</a></td>
<td class="sale">360.53</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KZTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KZTKRW', '32', event);" target="_parent">




					카자흐스탄 KZT

				</a></td>
<td class="sale">2.91</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.002</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BNDKRW', '33', event);" target="_parent">




					브루나이 BND

				</a></td>
<td class="sale">987.65</td>
<td>


						1,027.15

				</td>
<td>


						928.40

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.751</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_INRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_INRKRW', '34', event);" target="_parent">




					인도 INR

				</a></td>
<td class="sale">16.02</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PKRKRW', '35', event);" target="_parent">




					파키스탄 PKR

				</a></td>
<td class="sale">4.63</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BDTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BDTKRW', '36', event);" target="_parent">




					방글라데시 BDT

				</a></td>
<td class="sale">12.39</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.009</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PHPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PHPKRW', '37', event);" target="_parent">




					필리핀 PHP

				</a></td>
<td class="sale">23.51</td>
<td>


						25.86

				</td>
<td>


						21.59

				</td>
<td>


						23.74

				</td>
<td>


						23.28

				</td>
<td>0.018</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MXNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MXNKRW', '38', event);" target="_parent">




					멕시코 MXN

				</a></td>
<td class="sale">72.91</td>
<td>


						80.20

				</td>
<td>


						66.79

				</td>
<td>


						73.63

				</td>
<td>


						72.19

				</td>
<td>0.055</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BRLKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BRLKRW', '39', event);" target="_parent">




					브라질 BRL

				</a></td>
<td class="sale">263.80</td>
<td>


						290.70

				</td>
<td>


						237.42

				</td>
<td>

						N/A


				</td>
<td>


						260.64

				</td>
<td>0.201</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_VNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_VNDKRW', '40', event);" target="_parent">



					베트남 VND 100


				</a></td>
<td class="sale">5.60</td>
<td>


						6.26

				</td>
<td>


						4.94

				</td>
<td>


						5.65

				</td>
<td>


						5.55

				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ZARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ZARKRW', '41', event);" target="_parent">




					남아프리카 공화국 ZAR

				</a></td>
<td class="sale">72.49</td>
<td>


						78.28

				</td>
<td>


						66.70

				</td>
<td>


						73.35

				</td>
<td>


						71.63

				</td>
<td>0.055</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_RUBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_RUBKRW', '42', event);" target="_parent">




					러시아 RUB

				</a></td>
<td class="sale">16.08</td>
<td>


						17.60

				</td>
<td>


						13.27

				</td>
<td>


						16.64

				</td>
<td>


						15.52

				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HUFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HUFKRW', '43', event);" target="_parent">




					헝가리 HUF

				</a></td>
<td class="sale">3.89</td>
<td>


						4.25

				</td>
<td>


						3.58

				</td>
<td>


						3.93

				</td>
<td>


						3.85

				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PLNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PLNKRW', '44', event);" target="_parent">




					폴란드 PLN

				</a></td>
<td class="sale">311.40</td>
<td>


						336.31

				</td>
<td>


						286.49

				</td>
<td>


						314.82

				</td>
<td>


						307.98

				</td>
<td>0.237</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_LKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_LKRKRW', '45', event);" target="_parent">




					스리랑카 LKR

				</a></td>
<td class="sale">4.11</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DZDKRW', '46', event);" target="_parent">




					알제리 DZD

				</a></td>
<td class="sale">9.70</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KESKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KESKRW', '47', event);" target="_parent">




					케냐 KES

				</a></td>
<td class="sale">9.74</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_COPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_COPKRW', '48', event);" target="_parent">




					콜롬비아 COP

				</a></td>
<td class="sale">0.29</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>

In [9]:
# find는 html 안에서 해당 태그의 첫번째 정보를 출력
soup.find('tbody')

<tbody>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_USDKRW', '1', event);" target="_parent">




					미국 USD

				</a></td>
<td class="sale">1,315.30</td>
<td>


						1,338.31

				</td>
<td>


						1,292.29

				</td>
<td>


						1,328.10

				</td>
<td>


						1,302.50

				</td>
<td>1.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EURKRW', '2', event);" target="_parent">




					유럽연합 EUR

				</a></td>
<td class="sale">1,444.59</td>
<td>


						1,473.33

				</td>
<td>


						1,415.85

				</td>
<td>


						1,459.03

				</td>
<td>


						1,430.15

				</td>
<td>1.098</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JPYKRW', '3', event);" target="_parent">

					일본 JPY (100엔)




				</a></td>
<td class="sale">981.46</td>
<td>


						998.63

				</td>
<td>


						964.29

				</td>
<td>


						991.07

				</td>
<td>


						971.85

				</td>
<td>0.746</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CNYKRW', '4', event);" target="_parent">




					중국 CNY

				</a></td>
<td class="sale">191.35</td>
<td>


						200.91

				</td>
<td>


						181.79

				</td>
<td>


						193.26

				</td>
<td>


						189.44

				</td>
<td>0.146</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HKDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HKDKRW', '5', event);" target="_parent">




					홍콩 HKD

				</a></td>
<td class="sale">167.61</td>
<td>


						170.91

				</td>
<td>


						164.31

				</td>
<td>


						169.28

				</td>
<td>


						165.94

				</td>
<td>0.127</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TWDKRW', '6', event);" target="_parent">




					대만 TWD

				</a></td>
<td class="sale">43.13</td>
<td>


						48.78

				</td>
<td>


						38.82

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.033</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_GBPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_GBPKRW', '7', event);" target="_parent">




					영국 GBP

				</a></td>
<td class="sale">1,635.25</td>
<td>


						1,667.46

				</td>
<td>


						1,603.04

				</td>
<td>


						1,651.60

				</td>
<td>


						1,618.90

				</td>
<td>1.243</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_OMRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_OMRKRW', '8', event);" target="_parent">




					오만 OMR

				</a></td>
<td class="sale">3,416.19</td>
<td>


						3,720.23

				</td>
<td>


						3,211.22

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>2.597</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CADKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CADKRW', '9', event);" target="_parent">




					캐나다 CAD

				</a></td>
<td class="sale">982.63</td>
<td>


						1,001.98

				</td>
<td>


						963.28

				</td>
<td>


						992.45

				</td>
<td>


						972.81

				</td>
<td>0.747</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CHFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CHFKRW', '10', event);" target="_parent">




					스위스 CHF

				</a></td>
<td class="sale">1,467.80</td>
<td>


						1,496.71

				</td>
<td>


						1,438.89

				</td>
<td>


						1,482.47

				</td>
<td>


						1,453.13

				</td>
<td>1.116</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SEKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SEKKRW', '11', event);" target="_parent">




					스웨덴 SEK

				</a></td>
<td class="sale">127.62</td>
<td>


						130.74

				</td>
<td>


						124.50

				</td>
<td>


						128.89

				</td>
<td>


						126.35

				</td>
<td>0.097</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AUDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AUDKRW', '12', event);" target="_parent">




					호주 AUD

				</a></td>
<td class="sale">886.58</td>
<td>


						904.04

				</td>
<td>


						869.12

				</td>
<td>


						895.44

				</td>
<td>


						877.72

				</td>
<td>0.674</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NZDKRW', '13', event);" target="_parent">




					뉴질랜드 NZD

				</a></td>
<td class="sale">817.59</td>
<td>


						833.69

				</td>
<td>


						801.49

				</td>
<td>


						825.76

				</td>
<td>


						809.42

				</td>
<td>0.622</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CZKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CZKKRW', '14', event);" target="_parent">




					체코 CZK

				</a></td>
<td class="sale">61.61</td>
<td>


						66.84

				</td>
<td>


						56.07

				</td>
<td>


						62.28

				</td>
<td>


						60.94

				</td>
<td>0.047</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CLPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CLPKRW', '15', event);" target="_parent">




					칠레 CLP

				</a></td>
<td class="sale">1.65</td>
<td>


						1.81

				</td>
<td>


						1.49

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.001</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TRYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TRYKRW', '16', event);" target="_parent">




					튀르키예 TRY

				</a></td>
<td class="sale">67.81</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						68.55

				</td>
<td>


						67.07

				</td>
<td>0.052</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MNTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MNTKRW', '17', event);" target="_parent">




					몽골 MNT

				</a></td>
<td class="sale">0.37</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ILSKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ILSKRW', '18', event);" target="_parent">




					이스라엘 ILS

				</a></td>
<td class="sale">360.69</td>
<td>


						396.75

				</td>
<td>


						331.84

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DKKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DKKKRW', '19', event);" target="_parent">




					덴마크 DKK

				</a></td>
<td class="sale">193.86</td>
<td>


						198.60

				</td>
<td>


						189.12

				</td>
<td>


						195.79

				</td>
<td>


						191.93

				</td>
<td>0.147</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NOKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NOKKRW', '20', event);" target="_parent">




					노르웨이 NOK

				</a></td>
<td class="sale">125.62</td>
<td>


						128.69

				</td>
<td>


						122.55

				</td>
<td>


						126.87

				</td>
<td>


						124.37

				</td>
<td>0.096</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SARKRW', '21', event);" target="_parent">




					사우디아라비아 SAR

				</a></td>
<td class="sale">350.68</td>
<td>


						372.77

				</td>
<td>


						326.49

				</td>
<td>


						354.18

				</td>
<td>


						347.18

				</td>
<td>0.267</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KWDKRW', '22', event);" target="_parent">




					쿠웨이트 KWD

				</a></td>
<td class="sale">4,292.19</td>
<td>


						4,571.18

				</td>
<td>


						3,948.82

				</td>
<td>


						4,335.11

				</td>
<td>


						4,249.27

				</td>
<td>3.263</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BHDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BHDKRW', '23', event);" target="_parent">




					바레인 BHD

				</a></td>
<td class="sale">3,488.58</td>
<td>


						3,711.84

				</td>
<td>


						3,209.50

				</td>
<td>


						3,523.46

				</td>
<td>


						3,453.70

				</td>
<td>2.652</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AEDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AEDKRW', '24', event);" target="_parent">




					아랍에미리트 AED

				</a></td>
<td class="sale">358.16</td>
<td>


						377.85

				</td>
<td>


						333.45

				</td>
<td>


						361.74

				</td>
<td>


						354.58

				</td>
<td>0.272</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JODKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JODKRW', '25', event);" target="_parent">




					요르단 JOD

				</a></td>
<td class="sale">1,854.10</td>
<td>


						2,019.11

				</td>
<td>


						1,705.78

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>1.410</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EGPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EGPKRW', '26', event);" target="_parent">




					이집트 EGP

				</a></td>
<td class="sale">42.57</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.032</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_THBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_THBKRW', '27', event);" target="_parent">




					태국 THB

				</a></td>
<td class="sale">38.41</td>
<td>


						40.33

				</td>
<td>


						36.11

				</td>
<td>


						38.79

				</td>
<td>


						38.03

				</td>
<td>0.029</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SGDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SGDKRW', '28', event);" target="_parent">




					싱가포르 SGD

				</a></td>
<td class="sale">987.65</td>
<td>


						1,007.30

				</td>
<td>


						968.00

				</td>
<td>


						997.52

				</td>
<td>


						977.78

				</td>
<td>0.751</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MYRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MYRKRW', '29', event);" target="_parent">




					말레이시아 MYR

				</a></td>
<td class="sale">296.94</td>
<td>


						315.64

				</td>
<td>


						274.97

				</td>
<td>

						N/A


				</td>
<td>


						293.98

				</td>
<td>0.226</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_IDRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_IDRKRW', '30', event);" target="_parent">


					인도네시아 IDR 100



				</a></td>
<td class="sale">8.88</td>
<td>


						9.76

				</td>
<td>


						8.00

				</td>
<td>


						8.96

				</td>
<td>


						8.80

				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_QARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_QARKRW', '31', event);" target="_parent">




					카타르 QAR

				</a></td>
<td class="sale">360.53</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KZTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KZTKRW', '32', event);" target="_parent">




					카자흐스탄 KZT

				</a></td>
<td class="sale">2.91</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.002</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BNDKRW', '33', event);" target="_parent">




					브루나이 BND

				</a></td>
<td class="sale">987.65</td>
<td>


						1,027.15

				</td>
<td>


						928.40

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.751</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_INRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_INRKRW', '34', event);" target="_parent">




					인도 INR

				</a></td>
<td class="sale">16.02</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PKRKRW', '35', event);" target="_parent">




					파키스탄 PKR

				</a></td>
<td class="sale">4.63</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BDTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BDTKRW', '36', event);" target="_parent">




					방글라데시 BDT

				</a></td>
<td class="sale">12.39</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.009</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PHPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PHPKRW', '37', event);" target="_parent">




					필리핀 PHP

				</a></td>
<td class="sale">23.51</td>
<td>


						25.86

				</td>
<td>


						21.59

				</td>
<td>


						23.74

				</td>
<td>


						23.28

				</td>
<td>0.018</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MXNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MXNKRW', '38', event);" target="_parent">




					멕시코 MXN

				</a></td>
<td class="sale">72.91</td>
<td>


						80.20

				</td>
<td>


						66.79

				</td>
<td>


						73.63

				</td>
<td>


						72.19

				</td>
<td>0.055</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BRLKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BRLKRW', '39', event);" target="_parent">




					브라질 BRL

				</a></td>
<td class="sale">263.80</td>
<td>


						290.70

				</td>
<td>


						237.42

				</td>
<td>

						N/A


				</td>
<td>


						260.64

				</td>
<td>0.201</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_VNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_VNDKRW', '40', event);" target="_parent">



					베트남 VND 100


				</a></td>
<td class="sale">5.60</td>
<td>


						6.26

				</td>
<td>


						4.94

				</td>
<td>


						5.65

				</td>
<td>


						5.55

				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ZARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ZARKRW', '41', event);" target="_parent">




					남아프리카 공화국 ZAR

				</a></td>
<td class="sale">72.49</td>
<td>


						78.28

				</td>
<td>


						66.70

				</td>
<td>


						73.35

				</td>
<td>


						71.63

				</td>
<td>0.055</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_RUBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_RUBKRW', '42', event);" target="_parent">




					러시아 RUB

				</a></td>
<td class="sale">16.08</td>
<td>


						17.60

				</td>
<td>


						13.27

				</td>
<td>


						16.64

				</td>
<td>


						15.52

				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HUFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HUFKRW', '43', event);" target="_parent">




					헝가리 HUF

				</a></td>
<td class="sale">3.89</td>
<td>


						4.25

				</td>
<td>


						3.58

				</td>
<td>


						3.93

				</td>
<td>


						3.85

				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PLNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PLNKRW', '44', event);" target="_parent">




					폴란드 PLN

				</a></td>
<td class="sale">311.40</td>
<td>


						336.31

				</td>
<td>


						286.49

				</td>
<td>


						314.82

				</td>
<td>


						307.98

				</td>
<td>0.237</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_LKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_LKRKRW', '45', event);" target="_parent">




					스리랑카 LKR

				</a></td>
<td class="sale">4.11</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DZDKRW', '46', event);" target="_parent">




					알제리 DZD

				</a></td>
<td class="sale">9.70</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KESKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KESKRW', '47', event);" target="_parent">




					케냐 KES

				</a></td>
<td class="sale">9.74</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_COPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_COPKRW', '48', event);" target="_parent">




					콜롬비아 COP

				</a></td>
<td class="sale">0.29</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TZSKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TZSKRW', '49', event);" target="_parent">




					탄자니아 TZS

				</a></td>
<td class="sale">0.56</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NPRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NPRKRW', '50', event);" target="_parent">




					네팔 NPR

				</a></td>
<td class="sale">10.02</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.008</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_RONKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_RONKRW', '51', event);" target="_parent">




					루마니아 RON

				</a></td>
<td class="sale">292.58</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.222</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_LYDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_LYDKRW', '52', event);" target="_parent">




					리비아 LYD

				</a></td>
<td class="sale">275.90</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						278.65

				</td>
<td>


						273.15

				</td>
<td>0.210</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MOPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MOPKRW', '53', event);" target="_parent">





In [19]:
# find_all() 해당 태그의 전체 정보를 리스트의 형태로 출력

data_list = soup.find_all('td')

In [20]:
# data_list를 이용하여 2차원 배열로 새로운 리스트를 생성
# 1차원 리스트 생성
# [[7개씩],[7개씩],[7개씩],[] ...] -> 2차원 리스트

_list = []

for i in data_list :
    x = i.get_text()
    x = x.replace('\n', '')
    x = x.strip('\t')
    _list.append(x)
_list    

# 까지가 1차원 리스트

['미국 USD',
 '1,315.30',
 '1,338.31',
 '1,292.29',
 '1,328.10',
 '1,302.50',
 '1.000',
 '유럽연합 EUR',
 '1,444.59',
 '1,473.33',
 '1,415.85',
 '1,459.03',
 '1,430.15',
 '1.098',
 '일본 JPY (100엔)',
 '981.46',
 '998.63',
 '964.29',
 '991.07',
 '971.85',
 '0.746',
 '중국 CNY',
 '191.35',
 '200.91',
 '181.79',
 '193.26',
 '189.44',
 '0.146',
 '홍콩 HKD',
 '167.61',
 '170.91',
 '164.31',
 '169.28',
 '165.94',
 '0.127',
 '대만 TWD',
 '43.13',
 '48.78',
 '38.82',
 'N/A',
 'N/A',
 '0.033',
 '영국 GBP',
 '1,635.25',
 '1,667.46',
 '1,603.04',
 '1,651.60',
 '1,618.90',
 '1.243',
 '오만 OMR',
 '3,416.19',
 '3,720.23',
 '3,211.22',
 'N/A',
 'N/A',
 '2.597',
 '캐나다 CAD',
 '982.63',
 '1,001.98',
 '963.28',
 '992.45',
 '972.81',
 '0.747',
 '스위스 CHF',
 '1,467.80',
 '1,496.71',
 '1,438.89',
 '1,482.47',
 '1,453.13',
 '1.116',
 '스웨덴 SEK',
 '127.62',
 '130.74',
 '124.50',
 '128.89',
 '126.35',
 '0.097',
 '호주 AUD',
 '886.58',
 '904.04',
 '869.12',
 '895.44',
 '877.72',
 '0.674',
 '뉴질랜드 NZD',
 '817.59',
 '833.69',
 '801.49',
 '825.76',
 '809.42',
 '0.622',
 '체코 CZK',
 '61.61',
 '66.84',
 '56.07',
 '62.28',
 '60.94',
 '0.047',
 '칠레 CLP',
 '1.65',
 '1.81',
 '1.49',
 'N/A',
 'N/A',
 '0.001',
 '튀르키예 TRY',
 '67.81',
 'N/A',
 'N/A',
 '68.55',
 '67.07',
 '0.052',
 '몽골 MNT',
 '0.37',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '이스라엘 ILS',
 '360.69',
 '396.75',
 '331.84',
 'N/A',
 'N/A',
 '0.274',
 '덴마크 DKK',
 '193.86',
 '198.60',
 '189.12',
 '195.79',
 '191.93',
 '0.147',
 '노르웨이 NOK',
 '125.62',
 '128.69',
 '122.55',
 '126.87',
 '124.37',
 '0.096',
 '사우디아라비아 SAR',
 '350.68',
 '372.77',
 '326.49',
 '354.18',
 '347.18',
 '0.267',
 '쿠웨이트 KWD',
 '4,292.19',
 '4,571.18',
 '3,948.82',
 '4,335.11',
 '4,249.27',
 '3.263',
 '바레인 BHD',
 '3,488.58',
 '3,711.84',
 '3,209.50',
 '3,523.46',
 '3,453.70',
 '2.652',
 '아랍에미리트 AED',
 '358.16',
 '377.85',
 '333.45',
 '361.74',
 '354.58',
 '0.272',
 '요르단 JOD',
 '1,854.10',
 '2,019.11',
 '1,705.78',
 'N/A',
 'N/A',
 '1.410',
 '이집트 EGP',
 '42.57',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.032',
 '태국 THB',
 '38.41',
 '40.33',
 '36.11',
 '38.79',
 '38.03',
 '0.029',
 '싱가포르 SGD',
 '987.65',
 '1,007.30',
 '968.00',
 '997.52',
 '977.78',
 '0.751',
 '말레이시아 MYR',
 '296.94',
 '315.64',
 '274.97',
 'N/A',
 '293.98',
 '0.226',
 '인도네시아 IDR 100',
 '8.88',
 '9.76',
 '8.00',
 '8.96',
 '8.80',
 '0.007',
 '카타르 QAR',
 '360.53',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.274',
 '카자흐스탄 KZT',
 '2.91',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.002',
 '브루나이 BND',
 '987.65',
 '1,027.15',
 '928.40',
 'N/A',
 'N/A',
 '0.751',
 '인도 INR',
 '16.02',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.012',
 '파키스탄 PKR',
 '4.63',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.004',
 '방글라데시 BDT',
 '12.39',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.009',
 '필리핀 PHP',
 '23.51',
 '25.86',
 '21.59',
 '23.74',
 '23.28',
 '0.018',
 '멕시코 MXN',
 '72.91',
 '80.20',
 '66.79',
 '73.63',
 '72.19',
 '0.055',
 '브라질 BRL',
 '263.80',
 '290.70',
 '237.42',
 'N/A',
 '260.64',
 '0.201',
 '베트남 VND 100',
 '5.60',
 '6.26',
 '4.94',
 '5.65',
 '5.55',
 '0.004',
 '남아프리카 공화국 ZAR',
 '72.49',
 '78.28',
 '66.70',
 '73.35',
 '71.63',
 '0.055',
 '러시아 RUB',
 '16.08',
 '17.60',
 '13.27',
 '16.64',
 '15.52',
 '0.012',
 '헝가리 HUF',
 '3.89',
 '4.25',
 '3.58',
 '3.93',
 '3.85',
 '0.003',
 '폴란드 PLN',
 '311.40',
 '336.31',
 '286.49',
 '314.82',
 '307.98',
 '0.237',
 '스리랑카 LKR',
 '4.11',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.003',
 '알제리 DZD',
 '9.70',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.007',
 '케냐 KES',
 '9.74',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.007',
 '콜롬비아 COP',
 '0.29',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '탄자니아 TZS',
 '0.56',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '네팔 NPR',
 '10.02',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.008',
 '루마니아 RON',
 '292.58',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.222',
 '리비아 LYD',
 '275.90',
 'N/A',
 'N/A',
 '278.65',
 '273.15',
 '0.210',
 '마카오 MOP',
 '162.64',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.124',
 '미얀마 MMK',
 '0.63',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.001',
 '에티오피아 ETB',
 '24.14',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.018',
 '우즈베키스탄 UZS',
 '0.12',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '캄보디아 KHR',
 '0.32',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '피지 FJD',
 '596.29',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.453']

In [27]:
type(len(_list)//7)  # 몫만 추출하기때문에 dtype : int

int

In [25]:
list(range(0, (len(_list)//7),1))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57]

In [32]:
result = []
for i in range(0, len(_list)//7, 1) :
    x= []
    for j in range(i*7, (i+1)*7, 1) :
        x.append(_list[j])
    result.append(x)
result

[['미국 USD',
  '1,315.30',
  '1,338.31',
  '1,292.29',
  '1,328.10',
  '1,302.50',
  '1.000'],
 ['유럽연합 EUR',
  '1,444.59',
  '1,473.33',
  '1,415.85',
  '1,459.03',
  '1,430.15',
  '1.098'],
 ['일본 JPY (100엔)', '981.46', '998.63', '964.29', '991.07', '971.85', '0.746'],
 ['중국 CNY', '191.35', '200.91', '181.79', '193.26', '189.44', '0.146'],
 ['홍콩 HKD', '167.61', '170.91', '164.31', '169.28', '165.94', '0.127'],
 ['대만 TWD', '43.13', '48.78', '38.82', 'N/A', 'N/A', '0.033'],
 ['영국 GBP',
  '1,635.25',
  '1,667.46',
  '1,603.04',
  '1,651.60',
  '1,618.90',
  '1.243'],
 ['오만 OMR', '3,416.19', '3,720.23', '3,211.22', 'N/A', 'N/A', '2.597'],
 ['캐나다 CAD', '982.63', '1,001.98', '963.28', '992.45', '972.81', '0.747'],
 ['스위스 CHF',
  '1,467.80',
  '1,496.71',
  '1,438.89',
  '1,482.47',
  '1,453.13',
  '1.116'],
 ['스웨덴 SEK', '127.62', '130.74', '124.50', '128.89', '126.35', '0.097'],
 ['호주 AUD', '886.58', '904.04', '869.12', '895.44', '877.72', '0.674'],
 ['뉴질랜드 NZD', '817.59', '833.69', '801.49', '825.76', '809.42', '0.622'],
 ['체코 CZK', '61.61', '66.84', '56.07', '62.28', '60.94', '0.047'],
 ['칠레 CLP', '1.65', '1.81', '1.49', 'N/A', 'N/A', '0.001'],
 ['튀르키예 TRY', '67.81', 'N/A', 'N/A', '68.55', '67.07', '0.052'],
 ['몽골 MNT', '0.37', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['이스라엘 ILS', '360.69', '396.75', '331.84', 'N/A', 'N/A', '0.274'],
 ['덴마크 DKK', '193.86', '198.60', '189.12', '195.79', '191.93', '0.147'],
 ['노르웨이 NOK', '125.62', '128.69', '122.55', '126.87', '124.37', '0.096'],
 ['사우디아라비아 SAR', '350.68', '372.77', '326.49', '354.18', '347.18', '0.267'],
 ['쿠웨이트 KWD',
  '4,292.19',
  '4,571.18',
  '3,948.82',
  '4,335.11',
  '4,249.27',
  '3.263'],
 ['바레인 BHD',
  '3,488.58',
  '3,711.84',
  '3,209.50',
  '3,523.46',
  '3,453.70',
  '2.652'],
 ['아랍에미리트 AED', '358.16', '377.85', '333.45', '361.74', '354.58', '0.272'],
 ['요르단 JOD', '1,854.10', '2,019.11', '1,705.78', 'N/A', 'N/A', '1.410'],
 ['이집트 EGP', '42.57', 'N/A', 'N/A', 'N/A', 'N/A', '0.032'],
 ['태국 THB', '38.41', '40.33', '36.11', '38.79', '38.03', '0.029'],
 ['싱가포르 SGD', '987.65', '1,007.30', '968.00', '997.52', '977.78', '0.751'],
 ['말레이시아 MYR', '296.94', '315.64', '274.97', 'N/A', '293.98', '0.226'],
 ['인도네시아 IDR 100', '8.88', '9.76', '8.00', '8.96', '8.80', '0.007'],
 ['카타르 QAR', '360.53', 'N/A', 'N/A', 'N/A', 'N/A', '0.274'],
 ['카자흐스탄 KZT', '2.91', 'N/A', 'N/A', 'N/A', 'N/A', '0.002'],
 ['브루나이 BND', '987.65', '1,027.15', '928.40', 'N/A', 'N/A', '0.751'],
 ['인도 INR', '16.02', 'N/A', 'N/A', 'N/A', 'N/A', '0.012'],
 ['파키스탄 PKR', '4.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.004'],
 ['방글라데시 BDT', '12.39', 'N/A', 'N/A', 'N/A', 'N/A', '0.009'],
 ['필리핀 PHP', '23.51', '25.86', '21.59', '23.74', '23.28', '0.018'],
 ['멕시코 MXN', '72.91', '80.20', '66.79', '73.63', '72.19', '0.055'],
 ['브라질 BRL', '263.80', '290.70', '237.42', 'N/A', '260.64', '0.201'],
 ['베트남 VND 100', '5.60', '6.26', '4.94', '5.65', '5.55', '0.004'],
 ['남아프리카 공화국 ZAR', '72.49', '78.28', '66.70', '73.35', '71.63', '0.055'],
 ['러시아 RUB', '16.08', '17.60', '13.27', '16.64', '15.52', '0.012'],
 ['헝가리 HUF', '3.89', '4.25', '3.58', '3.93', '3.85', '0.003'],
 ['폴란드 PLN', '311.40', '336.31', '286.49', '314.82', '307.98', '0.237'],
 ['스리랑카 LKR', '4.11', 'N/A', 'N/A', 'N/A', 'N/A', '0.003'],
 ['알제리 DZD', '9.70', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['케냐 KES', '9.74', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['콜롬비아 COP', '0.29', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['탄자니아 TZS', '0.56', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['네팔 NPR', '10.02', 'N/A', 'N/A', 'N/A', 'N/A', '0.008'],
 ['루마니아 RON', '292.58', 'N/A', 'N/A', 'N/A', 'N/A', '0.222'],
 ['리비아 LYD', '275.90', 'N/A', 'N/A', '278.65', '273.15', '0.210'],
 ['마카오 MOP', '162.64', 'N/A', 'N/A', 'N/A', 'N/A', '0.124'],
 ['미얀마 MMK', '0.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.001'],
 ['에티오피아 ETB', '24.14', 'N/A', 'N/A', 'N/A', 'N/A', '0.018'],
 ['우즈베키스탄 UZS', '0.12', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['캄보디아 KHR', '0.32', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['피지 FJD', '596.29', 'N/A', 'N/A', 'N/A', 'N/A', '0.453']]

In [36]:
# 조금 더 simple하게 뽑아보자 
# list[x] : 리스트의 x위치
# list[x:y]: 리스트의 x 위치부터 y 전까지 

_list[]

'1.000'

In [37]:
result = []
for i in range(len(_list)//7) : 
    result.append(_list[i*7 : (i+1)*7])
result

[['미국 USD',
  '1,315.30',
  '1,338.31',
  '1,292.29',
  '1,328.10',
  '1,302.50',
  '1.000'],
 ['유럽연합 EUR',
  '1,444.59',
  '1,473.33',
  '1,415.85',
  '1,459.03',
  '1,430.15',
  '1.098'],
 ['일본 JPY (100엔)', '981.46', '998.63', '964.29', '991.07', '971.85', '0.746'],
 ['중국 CNY', '191.35', '200.91', '181.79', '193.26', '189.44', '0.146'],
 ['홍콩 HKD', '167.61', '170.91', '164.31', '169.28', '165.94', '0.127'],
 ['대만 TWD', '43.13', '48.78', '38.82', 'N/A', 'N/A', '0.033'],
 ['영국 GBP',
  '1,635.25',
  '1,667.46',
  '1,603.04',
  '1,651.60',
  '1,618.90',
  '1.243'],
 ['오만 OMR', '3,416.19', '3,720.23', '3,211.22', 'N/A', 'N/A', '2.597'],
 ['캐나다 CAD', '982.63', '1,001.98', '963.28', '992.45', '972.81', '0.747'],
 ['스위스 CHF',
  '1,467.80',
  '1,496.71',
  '1,438.89',
  '1,482.47',
  '1,453.13',
  '1.116'],
 ['스웨덴 SEK', '127.62', '130.74', '124.50', '128.89', '126.35', '0.097'],
 ['호주 AUD', '886.58', '904.04', '869.12', '895.44', '877.72', '0.674'],
 ['뉴질랜드 NZD', '817.59', '833.69', '801.49', '825.76', '809.42', '0.622'],
 ['체코 CZK', '61.61', '66.84', '56.07', '62.28', '60.94', '0.047'],
 ['칠레 CLP', '1.65', '1.81', '1.49', 'N/A', 'N/A', '0.001'],
 ['튀르키예 TRY', '67.81', 'N/A', 'N/A', '68.55', '67.07', '0.052'],
 ['몽골 MNT', '0.37', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['이스라엘 ILS', '360.69', '396.75', '331.84', 'N/A', 'N/A', '0.274'],
 ['덴마크 DKK', '193.86', '198.60', '189.12', '195.79', '191.93', '0.147'],
 ['노르웨이 NOK', '125.62', '128.69', '122.55', '126.87', '124.37', '0.096'],
 ['사우디아라비아 SAR', '350.68', '372.77', '326.49', '354.18', '347.18', '0.267'],
 ['쿠웨이트 KWD',
  '4,292.19',
  '4,571.18',
  '3,948.82',
  '4,335.11',
  '4,249.27',
  '3.263'],
 ['바레인 BHD',
  '3,488.58',
  '3,711.84',
  '3,209.50',
  '3,523.46',
  '3,453.70',
  '2.652'],
 ['아랍에미리트 AED', '358.16', '377.85', '333.45', '361.74', '354.58', '0.272'],
 ['요르단 JOD', '1,854.10', '2,019.11', '1,705.78', 'N/A', 'N/A', '1.410'],
 ['이집트 EGP', '42.57', 'N/A', 'N/A', 'N/A', 'N/A', '0.032'],
 ['태국 THB', '38.41', '40.33', '36.11', '38.79', '38.03', '0.029'],
 ['싱가포르 SGD', '987.65', '1,007.30', '968.00', '997.52', '977.78', '0.751'],
 ['말레이시아 MYR', '296.94', '315.64', '274.97', 'N/A', '293.98', '0.226'],
 ['인도네시아 IDR 100', '8.88', '9.76', '8.00', '8.96', '8.80', '0.007'],
 ['카타르 QAR', '360.53', 'N/A', 'N/A', 'N/A', 'N/A', '0.274'],
 ['카자흐스탄 KZT', '2.91', 'N/A', 'N/A', 'N/A', 'N/A', '0.002'],
 ['브루나이 BND', '987.65', '1,027.15', '928.40', 'N/A', 'N/A', '0.751'],
 ['인도 INR', '16.02', 'N/A', 'N/A', 'N/A', 'N/A', '0.012'],
 ['파키스탄 PKR', '4.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.004'],
 ['방글라데시 BDT', '12.39', 'N/A', 'N/A', 'N/A', 'N/A', '0.009'],
 ['필리핀 PHP', '23.51', '25.86', '21.59', '23.74', '23.28', '0.018'],
 ['멕시코 MXN', '72.91', '80.20', '66.79', '73.63', '72.19', '0.055'],
 ['브라질 BRL', '263.80', '290.70', '237.42', 'N/A', '260.64', '0.201'],
 ['베트남 VND 100', '5.60', '6.26', '4.94', '5.65', '5.55', '0.004'],
 ['남아프리카 공화국 ZAR', '72.49', '78.28', '66.70', '73.35', '71.63', '0.055'],
 ['러시아 RUB', '16.08', '17.60', '13.27', '16.64', '15.52', '0.012'],
 ['헝가리 HUF', '3.89', '4.25', '3.58', '3.93', '3.85', '0.003'],
 ['폴란드 PLN', '311.40', '336.31', '286.49', '314.82', '307.98', '0.237'],
 ['스리랑카 LKR', '4.11', 'N/A', 'N/A', 'N/A', 'N/A', '0.003'],
 ['알제리 DZD', '9.70', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['케냐 KES', '9.74', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['콜롬비아 COP', '0.29', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['탄자니아 TZS', '0.56', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['네팔 NPR', '10.02', 'N/A', 'N/A', 'N/A', 'N/A', '0.008'],
 ['루마니아 RON', '292.58', 'N/A', 'N/A', 'N/A', 'N/A', '0.222'],
 ['리비아 LYD', '275.90', 'N/A', 'N/A', '278.65', '273.15', '0.210'],
 ['마카오 MOP', '162.64', 'N/A', 'N/A', 'N/A', 'N/A', '0.124'],
 ['미얀마 MMK', '0.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.001'],
 ['에티오피아 ETB', '24.14', 'N/A', 'N/A', 'N/A', 'N/A', '0.018'],
 ['우즈베키스탄 UZS', '0.12', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['캄보디아 KHR', '0.32', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['피지 FJD', '596.29', 'N/A', 'N/A', 'N/A', 'N/A', '0.453']]

In [38]:
import pandas as pd

In [40]:
columns = ['통화명', '매매기준율', '현찰Buy', '현찰Sell', '송금보내', '송금받아', '미화환산율']

In [42]:
pd.DataFrame(result, columns=columns).to_csv('test.csv', index=False)

In [43]:
import mod_sql

In [110]:
db = mod_sql.Database('localhost', 'root', '1234', 'ubion7', 3306)

In [ ]:
# DB에 table생성 (naver)
# 필드는 7개 타입은 문자열 구성
# 통화명 필드는 primary key

sql = """
    create
    table
    `naver`
    (
    `통화명` varchar(32) primary key,
    `매매기준율` varchar(32),
    `현찰Buy` varchar(32),
    `현찰Sell` varchar(32),
    `송금보내` varchar(32),
    `송금받아` varchar(32),
    `미화환산율` varchar(32)
    )
"""

db.sql_query(sql)

In [48]:
# naver 라는 이름으로 생성한 테이블에 데이터 삽입 
# 데이터를 삽입하는 insert문을 작성

sql = """
    insert into `naver`
    values(
    '미국 USD',
    '1,315.30',
    '1,338.31',
    '1,292.29',
    '1,328.10',
    '1,302.50',
    '1.000'
    )
"""

db.sql_query(sql)

'Query OK'

In [49]:
sql = """
    select
    *
    from
    `naver`
"""

db.sql_query(sql)

      통화명     매매기준율     현찰Buy    현찰Sell      송금보내      송금받아  미화환산율
0  미국 USD  1,315.30  1,338.31  1,292.29  1,328.10  1,302.50  1.000

In [50]:
sql = """
    delete
    from
    `naver`
"""

db.sql_query(sql)

'Query OK'

In [53]:
# value값 데이터 없을 때는 이렇게밖에 안뜸

sql = """
    select
    *
    from
    `naver`
"""

db.sql_query(sql)

Empty DataFrame
Columns: []
Index: []

In [55]:
#Moon

sql = """
    insert
    into
    naver
    values
    (%s, %s, %s, %s, %s, %s, %s)
"""

values = [1,2,3,4,5,6,7]

db.sql_query(sql, values)

'Query OK'

In [56]:
sql = """
    select
    *
    from
    naver
"""

db.sql_query(sql)

  통화명 매매기준율 현찰Buy 현찰Sell 송금보내 송금받아 미화환산율
0   1     2     3      4    5    6     7

In [69]:
sql = """
    delete
    from
    `naver`
    
"""

db.sql_query(sql)

'Query OK'

In [58]:
result  # 2차원 리스트 형태

[['미국 USD',
  '1,315.30',
  '1,338.31',
  '1,292.29',
  '1,328.10',
  '1,302.50',
  '1.000'],
 ['유럽연합 EUR',
  '1,444.59',
  '1,473.33',
  '1,415.85',
  '1,459.03',
  '1,430.15',
  '1.098'],
 ['일본 JPY (100엔)', '981.46', '998.63', '964.29', '991.07', '971.85', '0.746'],
 ['중국 CNY', '191.35', '200.91', '181.79', '193.26', '189.44', '0.146'],
 ['홍콩 HKD', '167.61', '170.91', '164.31', '169.28', '165.94', '0.127'],
 ['대만 TWD', '43.13', '48.78', '38.82', 'N/A', 'N/A', '0.033'],
 ['영국 GBP',
  '1,635.25',
  '1,667.46',
  '1,603.04',
  '1,651.60',
  '1,618.90',
  '1.243'],
 ['오만 OMR', '3,416.19', '3,720.23', '3,211.22', 'N/A', 'N/A', '2.597'],
 ['캐나다 CAD', '982.63', '1,001.98', '963.28', '992.45', '972.81', '0.747'],
 ['스위스 CHF',
  '1,467.80',
  '1,496.71',
  '1,438.89',
  '1,482.47',
  '1,453.13',
  '1.116'],
 ['스웨덴 SEK', '127.62', '130.74', '124.50', '128.89', '126.35', '0.097'],
 ['호주 AUD', '886.58', '904.04', '869.12', '895.44', '877.72', '0.674'],
 ['뉴질랜드 NZD', '817.59', '833.69', '801.49', '825.76', '809.42', '0.622'],
 ['체코 CZK', '61.61', '66.84', '56.07', '62.28', '60.94', '0.047'],
 ['칠레 CLP', '1.65', '1.81', '1.49', 'N/A', 'N/A', '0.001'],
 ['튀르키예 TRY', '67.81', 'N/A', 'N/A', '68.55', '67.07', '0.052'],
 ['몽골 MNT', '0.37', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['이스라엘 ILS', '360.69', '396.75', '331.84', 'N/A', 'N/A', '0.274'],
 ['덴마크 DKK', '193.86', '198.60', '189.12', '195.79', '191.93', '0.147'],
 ['노르웨이 NOK', '125.62', '128.69', '122.55', '126.87', '124.37', '0.096'],
 ['사우디아라비아 SAR', '350.68', '372.77', '326.49', '354.18', '347.18', '0.267'],
 ['쿠웨이트 KWD',
  '4,292.19',
  '4,571.18',
  '3,948.82',
  '4,335.11',
  '4,249.27',
  '3.263'],
 ['바레인 BHD',
  '3,488.58',
  '3,711.84',
  '3,209.50',
  '3,523.46',
  '3,453.70',
  '2.652'],
 ['아랍에미리트 AED', '358.16', '377.85', '333.45', '361.74', '354.58', '0.272'],
 ['요르단 JOD', '1,854.10', '2,019.11', '1,705.78', 'N/A', 'N/A', '1.410'],
 ['이집트 EGP', '42.57', 'N/A', 'N/A', 'N/A', 'N/A', '0.032'],
 ['태국 THB', '38.41', '40.33', '36.11', '38.79', '38.03', '0.029'],
 ['싱가포르 SGD', '987.65', '1,007.30', '968.00', '997.52', '977.78', '0.751'],
 ['말레이시아 MYR', '296.94', '315.64', '274.97', 'N/A', '293.98', '0.226'],
 ['인도네시아 IDR 100', '8.88', '9.76', '8.00', '8.96', '8.80', '0.007'],
 ['카타르 QAR', '360.53', 'N/A', 'N/A', 'N/A', 'N/A', '0.274'],
 ['카자흐스탄 KZT', '2.91', 'N/A', 'N/A', 'N/A', 'N/A', '0.002'],
 ['브루나이 BND', '987.65', '1,027.15', '928.40', 'N/A', 'N/A', '0.751'],
 ['인도 INR', '16.02', 'N/A', 'N/A', 'N/A', 'N/A', '0.012'],
 ['파키스탄 PKR', '4.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.004'],
 ['방글라데시 BDT', '12.39', 'N/A', 'N/A', 'N/A', 'N/A', '0.009'],
 ['필리핀 PHP', '23.51', '25.86', '21.59', '23.74', '23.28', '0.018'],
 ['멕시코 MXN', '72.91', '80.20', '66.79', '73.63', '72.19', '0.055'],
 ['브라질 BRL', '263.80', '290.70', '237.42', 'N/A', '260.64', '0.201'],
 ['베트남 VND 100', '5.60', '6.26', '4.94', '5.65', '5.55', '0.004'],
 ['남아프리카 공화국 ZAR', '72.49', '78.28', '66.70', '73.35', '71.63', '0.055'],
 ['러시아 RUB', '16.08', '17.60', '13.27', '16.64', '15.52', '0.012'],
 ['헝가리 HUF', '3.89', '4.25', '3.58', '3.93', '3.85', '0.003'],
 ['폴란드 PLN', '311.40', '336.31', '286.49', '314.82', '307.98', '0.237'],
 ['스리랑카 LKR', '4.11', 'N/A', 'N/A', 'N/A', 'N/A', '0.003'],
 ['알제리 DZD', '9.70', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['케냐 KES', '9.74', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['콜롬비아 COP', '0.29', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['탄자니아 TZS', '0.56', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['네팔 NPR', '10.02', 'N/A', 'N/A', 'N/A', 'N/A', '0.008'],
 ['루마니아 RON', '292.58', 'N/A', 'N/A', 'N/A', 'N/A', '0.222'],
 ['리비아 LYD', '275.90', 'N/A', 'N/A', '278.65', '273.15', '0.210'],
 ['마카오 MOP', '162.64', 'N/A', 'N/A', 'N/A', 'N/A', '0.124'],
 ['미얀마 MMK', '0.63', 'N/A', 'N/A', 'N/A', 'N/A', '0.001'],
 ['에티오피아 ETB', '24.14', 'N/A', 'N/A', 'N/A', 'N/A', '0.018'],
 ['우즈베키스탄 UZS', '0.12', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['캄보디아 KHR', '0.32', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['피지 FJD', '596.29', 'N/A', 'N/A', 'N/A', 'N/A', '0.453']]

In [93]:
len(result)

58

In [119]:
# 변수 result의 데이터를 naver테이블에 삽입

sql = """
        insert into `naver`
        values
        (%s,%s,%s,%s,%s,%s,%s)
    """
for i in range(0, len(result), 1) : 
    
    
    db.sql_query(sql, result[i])

ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('미국 USD','1,315.30','1,338.31','1,292.29','1,328.10','1,302.50','1.000')' at line 3")

In [120]:
sql = """
        insert into `naver`
        values
        (%s,%s,%s,%s,%s,%s,%s)
        
    """
for i in result: 
    
    db.sql_query(sql, i)

In [104]:
sql = """
    delete
    from
    `naver`
    
"""

db.sql_query(sql)

'Query OK'

In [122]:
sql = """
    select
    *
    from
    naver
"""

db.sql_query(sql)

              통화명     매매기준율     현찰Buy    현찰Sell      송금보내      송금받아  미화환산율
0   남아프리카 공화국 ZAR     72.49     78.28     66.70     73.35     71.63  0.055
1          네팔 NPR     10.02       N/A       N/A       N/A       N/A  0.008
2        노르웨이 NOK    125.62    128.69    122.55    126.87    124.37  0.096
3        뉴질랜드 NZD    817.59    833.69    801.49    825.76    809.42  0.622
4          대만 TWD     43.13     48.78     38.82       N/A       N/A  0.033
5         덴마크 DKK    193.86    198.60    189.12    195.79    191.93  0.147
6         러시아 RUB     16.08     17.60     13.27     16.64     15.52  0.012
7        루마니아 RON    292.58       N/A       N/A       N/A       N/A  0.222
8         리비아 LYD    275.90       N/A       N/A    278.65    273.15  0.210
9         마카오 MOP    162.64       N/A       N/A       N/A       N/A  0.124
10      말레이시아 MYR    296.94    315.64    274.97       N/A    293.98  0.226
11        멕시코 MXN     72.91     80.20     66.79     73.63     72.19  0.055
12         몽골 MNT      0.37       N/A       N/A       N/A       N/A  0.000
13         미국 USD  1,315.30  1,338.31  1,292.29  1,328.10  1,302.50  1.000
14        미얀마 MMK      0.63       N/A       N/A       N/A       N/A  0.001
15        바레인 BHD  3,488.58  3,711.84  3,209.50  3,523.46  3,453.70  2.652
16      방글라데시 BDT     12.39       N/A       N/A       N/A       N/A  0.009
17    베트남 VND 100      5.60      6.26      4.94      5.65      5.55  0.004
18        브라질 BRL    263.80    290.70    237.42       N/A    260.64  0.201
19       브루나이 BND    987.65  1,027.15    928.40       N/A       N/A  0.751
20    사우디아라비아 SAR    350.68    372.77    326.49    354.18    347.18  0.267
21       스리랑카 LKR      4.11       N/A       N/A       N/A       N/A  0.003
22        스웨덴 SEK    127.62    130.74    124.50    128.89    126.35  0.097
23        스위스 CHF  1,467.80  1,496.71  1,438.89  1,482.47  1,453.13  1.116
24       싱가포르 SGD    987.65  1,007.30    968.00    997.52    977.78  0.751
25     아랍에미리트 AED    358.16    377.85    333.45    361.74    354.58  0.272
26        알제리 DZD      9.70       N/A       N/A       N/A       N/A  0.007
27      에티오피아 ETB     24.14       N/A       N/A       N/A       N/A  0.018
28         영국 GBP  1,635.25  1,667.46  1,603.04  1,651.60  1,618.90  1.243
29         오만 OMR  3,416.19  3,720.23  3,211.22       N/A       N/A  2.597
30        요르단 JOD  1,854.10  2,019.11  1,705.78       N/A       N/A  1.410
31     우즈베키스탄 UZS      0.12       N/A       N/A       N/A       N/A  0.000
32       유럽연합 EUR  1,444.59  1,473.33  1,415.85  1,459.03  1,430.15  1.098
33       이스라엘 ILS    360.69    396.75    331.84       N/A       N/A  0.274
34        이집트 EGP     42.57       N/A       N/A       N/A       N/A  0.032
35         인도 INR     16.02       N/A       N/A       N/A       N/A  0.012
36  인도네시아 IDR 100      8.88      9.76      8.00      8.96      8.80  0.007
37  일본 JPY (100엔)    981.46    998.63    964.29    991.07    971.85  0.746
38         중국 CNY    191.35    200.91    181.79    193.26    189.44  0.146
39         체코 CZK     61.61     66.84     56.07     62.28     60.94  0.047
40         칠레 CLP      1.65      1.81      1.49       N/A       N/A  0.001
41      카자흐스탄 KZT      2.91       N/A       N/A       N/A       N/A  0.002
42        카타르 QAR    360.53       N/A       N/A       N/A       N/A  0.274
43       캄보디아 KHR      0.32       N/A       N/A       N/A       N/A  0.000
44        캐나다 CAD    982.63  1,001.98    963.28    992.45    972.81  0.747
45         케냐 KES      9.74       N/A       N/A       N/A       N/A  0.007
46       콜롬비아 COP      0.29       N/A       N/A       N/A       N/A  0.000
47       쿠웨이트 KWD  4,292.19  4,571.18  3,948.82  4,335.11  4,249.27  3.263
48       탄자니아 TZS      0.56       N/A       N/A       N/A       N/A  0.000
49         태국 THB     38.41     40.33     36.11     38.79     38.03  0.029
50       튀르키예 TRY     67.81       N/A       N/A     68.55     67.07  0.052
51       파키스탄 PKR      4.63       N/A       N/A       N/A       N/A  0.004
52        폴란드 PLN    311.40    336.31    286.49    314.82    307.98  0.237
53         피지 FJD    596.29       N/A       N/A       N/A       N/A  0.453
54        필리핀 PHP     23.51     25.86     21.59     23.74     23.28  0.018
55        헝가리 HUF      3.89      4.25      3.58      3.93      3.85  0.003
56         호주 AUD    886.58    904.04    869.12    895.44    877.72  0.674
57         홍콩 HKD    167.61    170.91    164.31    169.28    165.94  0.127

In [142]:
# 위 결과 보면, 통화명 순서가 가나다 순으로 자동 정리돼써
    # 그냥 우리가 넣는 순서대로 만들고싶다면? 
# workbench -> table생성시 `no`컬럼에 AI 에 체크 ! -> 자동 인덱스 생성(들어온순서대로 자동 넘버링)
        # 이유는 모르겠으나, insert한 순서대로 열 생성 
    # 단, AI check한 no 컬럼의 숫자는 중간에 data 지워도 그다음 숫자부터 시작됨 
    # it's like 게시판의 게시물번호  


sql = """
        insert into `naver2`
        (`통화명`, `매매기준율`, `현찰(구매)`, `현찰(판매)`, `송금(보낼때)`, `송금(받을때)`, `미화환산율`)
        values
        (%s,%s,%s,%s,%s,%s,%s)
        
    """
for i in result: 
    
    db.sql_query(sql, i)

In [141]:
sql = """
    delete
    from
    `naver2`
    
"""

db.sql_query(sql)

'Query OK'

In [145]:
sql = """
    select
    *
    from
    naver2
"""

db.sql_query(sql)

,no,통화명,매매기준율,현찰(구매),현찰(판매),송금(보낼때),송금(받을때),미화환산율
0,233,미국 USD,"1,315.30","1,338.31","1,292.29","1,328.10","1,302.50",1.000
1,234,유럽연합 EUR,"1,444.59","1,473.33","1,415.85","1,459.03","1,430.15",1.098
2,235,일본 JPY (100엔),981.46,998.63,964.29,991.07,971.85,0.746
3,236,중국 CNY,191.35,200.91,181.79,193.26,189.44,0.146
4,237,홍콩 HKD,167.61,170.91,164.31,169.28,165.94,0.127
5,238,대만 TWD,43.13,48.78,38.82,N/A,N/A,0.033
6,239,영국 GBP,"1,635.25","1,667.46","1,603.04","1,651.60","1,618.90",1.243
7,240,오만 OMR,"3,416.19","3,720.23","3,211.22",N/A,N/A,2.597
8,241,캐나다 CAD,982.63,"1,001.98",963.28,992.45,972.81,0.747
9,242,스위스 CHF,"1,467.80","1,496.71","1,438.89","1,482.47","1,453.13",1.116
10,243,스웨덴 SEK,127.62,130.74,124.50,128.89,126.35,0.097
11,244,호주 AUD,886.58,904.04,869.12,895.44,877.72,0.674
12,245,뉴질랜드 NZD,817.59,833.69,801.49,825.76,809.42,0.622
13,246,체코 CZK,61.61,66.84,56.07,62.28,60.94,0.047
14,247,칠레 CLP,1.65,1.81,1.49,N/A,N/A,0.001
15,248,튀르키예 TRY,67.81,N/A,N/A,68.55,67.07,0.052
16,249,몽골 MNT,0.37,N/A,N/A,N/A,N/A,0.000
17,250,이스라엘 ILS,360.69,396.75,331.84,N/A,N/A,0.274
18,251,덴마크 DKK,193.86,198.60,189.12,195.79,191.93,0.147
19,252,노르웨이 NOK,125.62,128.69,122.55,126.87,124.37,0.096
20,253,사우디아라비아 SAR,350.68,372.77,326.49,354.18,347.18,0.267
21,254,쿠웨이트 KWD,"4,292.19","4,571.18","3,948.82","4,335.11","4,249.27",3.263
22,255,바레인 BHD,"3,488.58","3,711.84","3,209.50","3,523.46","3,453.70",2.652
23,256,아랍에미리트 AED,358.16,377.85,333.45,361.74,354.58,0.272
24,257,요르단 JOD,"1,854.10","2,019.11","1,705.78",N/A,N/A,1.410
25,258,이집트 EGP,42.57,N/A,N/A,N/A,N/A,0.032
26,259,태국 THB,38.41,40.33,36.11,38.79,38.03,0.029
27,260,싱가포르 SGD,987.65,"1,007.30",968.00,997.52,977.78,0.751
28,261,말레이시아 MYR,296.94,315.64,274.97,N/A,293.98,0.226
29,262,인도네시아 IDR 100,8.88,9.76,8.00,8.96,8.80,0.007
30,263,카타르 QAR,360.53,N/A,N/A,N/A,N/A,0.274
31,264,카자흐스탄 KZT,2.91,N/A,N/A,N/A,N/A,0.002
32,265,브루나이 BND,987.65,"1,027.15",928.40,N/A,N/A,0.751
33,266,인도 INR,16.02,N/A,N/A,N/A,N/A,0.012
34,267,파키스탄 PKR,4.63,N/A,N/A,N/A,N/A,0.004
35,268,방글라데시 BDT,12.39,N/A,N/A,N/A,N/A,0.009
36,269,필리핀 PHP,23.51,25.86,21.59,23.74,23.28,0.018
37,270,멕시코 MXN,72.91,80.20,66.79,73.63,72.19,0.055
38,271,브라질 BRL,263.80,290.70,237.42,N/A,260.64,0.201
39,272,베트남 VND 100,5.60,6.26,4.94,5.65,5.55,0.004
40,273,남아프리카 공화국 ZAR,72.49,78.28,66.70,73.35,71.63,0.055
41,274,러시아 RUB,16.08,17.60,13.27,16.64,15.52,0.012
42,275,헝가리 HUF,3.89,4.25,3.58,3.93,3.85,0.003
43,276,폴란드 PLN,311.40,336.31,286.49,314.82,307.98,0.237
44,277,스리랑카 LKR,4.11,N/A,N/A,N/A,N/A,0.003
45,278,알제리 DZD,9.70,N/A,N/A,N/A,N/A,0.007
46,279,케냐 KES,9.74,N/A,N/A,N/A,N/A,0.007
47,280,콜롬비아 COP,0.29,N/A,N/A,N/A,N/A,0.000
48,281,탄자니아 TZS,0.56,N/A,N/A,N/A,N/A,0.000
49,282,네팔 NPR,10.02,N/A,N/A,N/A,N/A,0.008
50,283,루마니아 RON,292.58,N/A,N/A,N/A,N/A,0.222
51,284,리비아 LYD,275.90,N/A,N/A,278.65,273.15,0.210
52,285,마카오 MOP,162.64,N/A,N/A,N/A,N/A,0.124
53,286,미얀마 MMK,0.63,N/A,N/A,N/A,N/A,0.001
54,287,에티오피아 ETB,24.14,N/A,N/A,N/A,N/A,0.018
55,288,우즈베키스탄 UZS,0.12,N/A,N/A,N/A,N/A,0.000
56,289,캄보디아 KHR,0.32,N/A,N/A,N/A,N/A,0.000
57,290,피지 FJD,596.29,N/A,N/A,N/A,N/A,0.453

In [146]:
db.sql_close()